#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for utils/monitor
#
# IDENTIFICATION
#    src/backend/utils/monitor/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/utils/monitor
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	monitor_event.o

include $(top_srcdir)/src/backend/common.mk
